#!/bin/csh -f
setenv LIBXML2_HOME /usr/include/libxml2 
setenv PATH /usr/bin:/DLR/TIVA/local/bin:/sc/bin:/usr/include:/usr/include/libxml2":"$PATH
rehash
cd Src
make -f Makefile.linux dynamic
cd ../Doc
doxygen
cd ..

scons Pack=yes FC=g77 -c .
scons Pack=yes FC=g77 
