#!/bin/csh -f
setenv LIBXML2_HOME /sc 
setenv PATH /usr/bin:/DLR/TIVA/local/bin:/sc/bin":"$PATH
rehash
cd Src
make -f Makefile.linux dynamic
cd ../Doc
doxygen
cd ..

scons Pack=yes FC=g77 -c .
scons Pack=yes FC=g77 

