LD = gcc
CC = gcc
CCFLAGS = -g
CPPFLAGS = -I../Src -I/usr/include/libxml2
LDFLAGS =  

LIBS = -L../lib -lTIXI -lxslt -lxml2 -lz -lpthread -lm -ldl 



.c.o:
	$(CC) $(CCFLAGS) $(CPPFLAGS) -c -o $*.o $<

all: tixiC 

tixiC:	 tixiDemo.o
	$(LD) -o tixiC tixiDemo.o $(LDFLAGS) $(LIBS) 
clean:
	$(RM) *.o
