LD = gcc
CC = gcc
CCFLAGS = -g
CPPFLAGS = -I../include
LDFLAGS = -static 

LIBS = -L../lib -lTIXI -lxml2 -lz -lpthread -lm



.c.o:
	$(CC) $(CCFLAGS) $(CPPFLAGS) -c -o $*.o $<

all: tixiC 

tixiC:	 tixiDemo.o
	$(LD) -o tixiC tixiDemo.o $(LDFLAGS) $(LIBS) 
clean:
	$(RM) *.o
