LD = gcc
FC= g77
CC= gcc
CCFLAGS = -g
FCFLAGS = -g
CPPFLAGS = -I../include
LDFLAGS = -static 

LIBS = -L../lib -L../lib-static-gcc-win32 -lTIXI -lxml2 -llibxslt -llibcurl_imp

.c.o:
	$(CC) $(CCFLAGS) $(CPPFLAGS) -c -o $*.o $<
.f.o:
	$(FC) $(FCFLAGS) $(CPPFLAGS) -c -o $*.o  $<

all: tixiC tixi77

tixiC:	 tixiDemo.o
	$(LD) -o tixiC tixiDemo.o $(LDFLAGS) $(LIBS) 
tixi77:  testf77.o 
	$(FC) -o tixi77 testf77.o $(LDFLAGS) -L../lib -lTIXIf $(LIBS) 
clean:
	$(RM) *.o
